server.port=8084
spring.application.name=ecomK
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=*
#Here it is exposing all the endpoint ,We can select particular endpit to show.like->
#management.endpoints.web.exposure.include=beans(only beans endpoint wil be visible).
management.endpoint.health.show-details=always

management.info.env.enabled=true
info.app.name=ecomK
info.app.description=Place to buy classy product
info.app.version=1.0.2
management.endpoint.shutdown.enabled=true
management.server.shutdown=graceful